import React from 'react';
import { FileText, Download, Eye } from 'lucide-react';

const ReportsTable = ({ reports, loading }) => {
  return (
    <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden flex-1 flex flex-col h-full">
      <div className="overflow-x-auto flex-1">
        <table className="w-full text-left text-sm text-slate-600">
          <thead className="bg-slate-50 text-xs uppercase font-semibold text-slate-500 sticky top-0 z-10 border-b border-slate-200">
            <tr>
              <th className="px-4 py-3 sm:px-6 sm:py-4">Report ID</th>
              <th className="px-4 py-3 sm:px-6 sm:py-4">Type</th>
              <th className="px-4 py-3 sm:px-6 sm:py-4 hidden sm:table-cell">Generated By</th>
              <th className="px-4 py-3 sm:px-6 sm:py-4 hidden md:table-cell">Date</th>
              <th className="px-4 py-3 sm:px-6 sm:py-4">Status</th>
              <th className="px-4 py-3 sm:px-6 sm:py-4 text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-200">
            {loading ? (
              [1, 2, 3].map(i => (
                <tr key={i} className="animate-pulse">
                  <td className="px-4 py-3 sm:px-6 sm:py-4"><div className="h-4 bg-slate-200 rounded w-1/2"></div></td>
                  <td className="px-4 py-3 sm:px-6 sm:py-4"><div className="h-4 bg-slate-200 rounded w-3/4"></div></td>
                  <td className="px-4 py-3 sm:px-6 sm:py-4 hidden sm:table-cell"><div className="h-4 bg-slate-200 rounded w-1/2"></div></td>
                  <td className="px-4 py-3 sm:px-6 sm:py-4 hidden md:table-cell"><div className="h-4 bg-slate-200 rounded w-2/3"></div></td>
                  <td className="px-4 py-3 sm:px-6 sm:py-4"><div className="h-4 bg-slate-200 rounded w-full"></div></td>
                  <td className="px-4 py-3 sm:px-6 sm:py-4"><div className="h-4 bg-slate-200 rounded w-1/4 ml-auto"></div></td>
                </tr>
              ))
            ) : (
              reports.map(report => (
                <tr key={report.id} className="hover:bg-slate-50 transition-colors">
                  <td className="px-4 py-3 sm:px-6 sm:py-4 font-mono text-xs font-bold text-slate-700">
                    {report.id}
                  </td>
                  <td className="px-4 py-3 sm:px-6 sm:py-4 font-semibold text-slate-800">
                    {report.type}
                  </td>
                  <td className="px-4 py-3 sm:px-6 sm:py-4 hidden sm:table-cell font-medium">
                    {report.generatedBy}
                  </td>
                  <td className="px-4 py-3 sm:px-6 sm:py-4 hidden md:table-cell font-medium">
                    {report.date}
                  </td>
                  <td className="px-4 py-3 sm:px-6 sm:py-4">
                     <span className={`text-[10px] font-bold px-2.5 py-1 rounded-full whitespace-nowrap ${
                       report.status === 'Action Required' ? 'bg-rose-100 text-rose-700' :
                       report.status === 'Pending Approval' ? 'bg-amber-100 text-amber-700' :
                       'bg-emerald-100 text-emerald-700'
                     }`}>
                       {report.status}
                     </span>
                  </td>
                  <td className="px-4 py-3 sm:px-6 sm:py-4 text-right">
                    <div className="flex justify-end gap-2">
                       <button className="p-1.5 text-slate-400 hover:text-teal-600 hover:bg-teal-50 rounded transition-colors" title="View">
                         <Eye className="w-4 h-4" />
                       </button>
                       <button className="p-1.5 text-slate-400 hover:text-indigo-600 hover:bg-indigo-50 rounded transition-colors" title="Download PDF">
                         <Download className="w-4 h-4" />
                       </button>
                    </div>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
};

export default ReportsTable;
